NON_MAP_ITEMS = [
    {
        "name": "Progressive Pan/Zoom/Move",
        "progression": True,
        "count": 3,
        "category": ["Features"],
    },
    {
        "name": "Compass",
        "progression": True,
        "count": 1,
        "category": ["Features"],
    },
    {
        "name": "Car visibility",
        "progression": True,
        "count": 1,
        "category": ["Features"],
    },
    {
        "name": "Map Fragment",
        "count": 21,
        "useful": True,
        "category": ["Maps"],
    },
    {"name": "Terrain Map View", "progression": True, "category": ["Features"]},
    {"name": "Satellite Map View", "progression": True, "category": ["Features"]},
    {"name": "OpenStreetMap View", "useful": True, "category": ["Features"]},
    {"name": "Fast Driving", "useful": True, "category": ["Features"]},
    {"name": "Show Author Names", "useful": True, "category": ["Features"]},
    {"name": "Score Boost +500", "useful": True, "count": 30, "category": ["Boosts"]},
    {"name": "+10 seconds", "progression": True, "count": 62, "category": ["Features"]},
    {"name": "20 Second Timer Trap", "count": 3, "trap": True, "category": ["Traps"]},
    # {"name": "Death Metal Map Trap", "count": 1, "trap": True, "category": ["Traps"]},
    # {"name": "Labelless Trap", "count": 1, "trap": True, "category": ["Traps"]},
    {"name": "Mega Plonk Trap", "count": 3, "trap": True, "category": ["Traps"]},
]
