non_map_items = [
    {
        "name": "Progressive Pan/Zoom/Move",
        "progression": True,
        "count": 3,
        "category": ["Features"],
    },
    {
        "name": "Compass",
        "progression": True,
        "count": 1,
        "category": ["Features"],
    },
    {
        "name": "Car visibility",
        "progression": True,
        "count": 1,
        "category": ["Features"],
    },
    {"name": "Terrain Map View", "progression": True, "category": ["Features"]},
    {"name": "Satellite Map View", "progression": True, "category": ["Features"]},
    {"name": "OpenStreetMap View", "useful": True, "category": ["Features"]},
    {"name": "Fast driving", "useful": True, "category": ["Features"]},
    {"name": "Show Author Names", "useful": True, "category": ["Features"]},
    {"name": "Score Boost +1000", "useful": True, "count": 20, "category": ["Boosts"]},
    {"name": "+20 Seconds", "progression": True, "count": 31, "category": ["Features"]},
    {"name": "20 Second Timer Trap", "count": 2, "trap": True, "category": ["Traps"]},
    {"name": "Death Metal Map Trap", "count": 1, "trap": True, "category": ["Traps"]},
    {"name": "Labelless Trap", "count": 1, "trap": True, "category": ["Traps"]},
    {"name": "Mega Plonk Trap", "count": 3, "trap": True, "category": ["Traps"]},
    {"name": "Space Plonk Trap", "count": 1, "trap": True, "category": ["Traps"]},
]
